# Generated by Django 5.0.4 on 2024-05-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('vivienda', models.TextField(max_length=100)),
                ('tipo', models.TextField(max_length=100)),
                ('precio', models.IntegerField()),
                ('proyeccion', models.IntegerField()),
                ('consumo', models.IntegerField()),
                ('panel', models.IntegerField()),
            ],
        ),
    ]
